FROM php:7.4-fpm

RUN mv "$PHP_INI_DIR/php.ini-development" "$PHP_INI_DIR/php.ini"
RUN usermod -u 1000 www-data;
RUN groupmod -g 1000 www-data;
RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar;
RUN chmod +x wp-cli.phar;
RUN mv wp-cli.phar /usr/local/bin/wp;

RUN pecl install xdebug;
RUN docker-php-ext-enable xdebug;
RUN docker-php-ext-install mysqli;

RUN apt-get update;
RUN apt-get install -y zip git rsync python3 subversion mariadb-client openssh-client sudo jq;
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');";
RUN php -r "if (hash_file('sha384', 'composer-setup.php') === '55ce33d7678c5a611085589f1f3ddf8b3c52d662cd01d4ba75c0ee0459970c2200a51f492d557530c71c15d8dba01eae') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;";
RUN php composer-setup.php --install-dir=/usr/local/bin --filename=composer;
RUN php -r "unlink('composer-setup.php');";

RUN curl -sL https://deb.nodesource.com/setup_16.x | bash -
RUN apt-get install nodejs

RUN chown -R 1000:1000 /var/www

USER 1000
